name: 'Tecture - Component Library Publisher'
description: 'Publishes architectural component library to tecture'
author: 'tecture.io'
inputs:
  milliseconds: # change this
    required: true
    description: 'milliseconds to wait'
    default: '1000'
runs:
  using: 'node16'
  main: 'dist/index.js'
