name: Build and Bump Version

on:
  push:
    branches:
      - main

jobs:
  build_and_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Bump version and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "New build"
#          yarn config set version-tag-prefix "v"
#          yarn version --patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: git push --follow-tags
